# Load user includes
if [ -f ~/.includes.zsh ]; then
  source ~/.includes.zsh
fi

# Prompts and history tools
eval "$(starship init zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"
eval "$(fzf --zsh)"
#eval "$(gh copilot alias -- zsh)"

set -o vi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
